import SwiftUI

@MainActor
final class SituationSceneViewModel: ObservableObject {
  @Published private(set) var characterImageData: Data?
  @Published private(set) var backgroundImageData: Data?
  @Published private(set) var isPreparing = false
  @Published private(set) var errorMessage: String?

  private let imageClient = AvatarGenerationAPIClient()
  private let cache = GeneratedMediaCache.shared
  private static var backgroundGenerationTasks: [String: Task<Data?, Never>] = [:]

  /// Starts loading the location as soon as the learner selects a node. The
  /// task is shared with the mission and speaking screens, so the artwork is
  /// ready before a newly created character enters the scene.
  func prefetchBackground(for situation: Situation) async {
    guard situation.locationBackgroundAsset == nil else { return }
    _ = await backgroundImage(for: situation)
  }

  func prepare(for situation: Situation, character: Character?) async {
    guard !isPreparing else { return }
    isPreparing = true
    errorMessage = nil
    defer { isPreparing = false }

    let characterCacheKey =
      character?.portraitCacheKey ?? "character-\(situation.characterID)-cutout-v5"
    // A saved character is the source of truth for the scene. Read its image
    // before the disk cache, otherwise an older portrait for the same template
    // can replace the learner's new name/gender choices.
    if let sourceAvatar = character?.avatarImageData {
      // Characters saved before cutout-v4 may still be opaque. Process them
      // once more before showing the game scene, then reuse the transparent
      // PNG for every later encounter.
      let cutout =
        AvatarGenerationAPIClient.transparentAvatarPNG(from: sourceAvatar) ?? sourceAvatar
      characterImageData = cutout
      cache.save(cutout, for: characterCacheKey)
    } else if let cachedAvatar = cache.imageData(for: characterCacheKey) {
      characterImageData = cachedAvatar
    } else if let sourceAvatar = cache.imageData(for: "character-\(situation.characterID)") {
      // Legacy fallback for portraits generated by an earlier app version.
      let cutout =
        AvatarGenerationAPIClient.transparentAvatarPNG(from: sourceAvatar) ?? sourceAvatar
      characterImageData = cutout
      cache.save(cutout, for: characterCacheKey)
    } else {
      characterImageData = nil
    }
    if situation.locationBackgroundAsset == nil {
      backgroundImageData = await backgroundImage(for: situation)
    } else {
      backgroundImageData = nil
    }

    if backgroundImageData == nil && situation.locationBackgroundAsset == nil {
      errorMessage =
        "Some scene artwork could not be generated. You can still practice with the illustrated fallback."
    }
  }

  private func backgroundImage(for situation: Situation) async -> Data? {
    let key = "location-\(situation.locationID)"
    if let cached = cache.imageData(for: key) { return cached }

    if let existingRequest = Self.backgroundGenerationTasks[key] {
      return await existingRequest.value
    }

    let imageClient = imageClient
    let cache = cache
    let request = Task<Data?, Never> {
      do {
        let generated = try await imageClient.generateLocation(
          named: situation.locationName,
          description: situation.locationPrompt
        )
        cache.save(generated, for: key)
        return generated
      } catch {
        return nil
      }
    }
    Self.backgroundGenerationTasks[key] = request
    let generatedImage = await request.value
    Self.backgroundGenerationTasks[key] = nil
    return generatedImage
  }
}
