import Foundation

/// Codable source of truth for a learner-specific roadmap generated by AI.
/// It is persisted locally and converted into the SwiftUI runtime models.
struct StudyPathDefinition: Codable, Equatable {
  let chapters: [StudyPathChapterDefinition]

  var isValid: Bool {
    let orderedChapters = chapters.sorted { (Int($0.id) ?? 0) < (Int($1.id) ?? 0) }
    return orderedChapters.count == 5
      && orderedChapters.enumerated().allSatisfy { chapterIndex, chapter in
        chapter.id == String(chapterIndex + 1)
          && chapter.situations.count == 10
          && chapter.situations.allSatisfy { $0.chapterID == chapter.id }
      }
      && orderedChapters.flatMap(\.situations).sorted {
        (Int($0.id) ?? 0) < (Int($1.id) ?? 0)
      }.map(\.id) == (1...50).map { String($0) }
  }
}

struct StudyPathChapterDefinition: Codable, Equatable {
  let id: String
  let title: String
  let subtitle: String
  let icon: String
  let situations: [StudyPathSituationDefinition]
}

struct StudyPathSituationDefinition: Codable, Equatable {
  let id: String
  let chapterID: String
  let title: String
  let subtitle: String
  let story: String
  let icon: String
  let imageAsset: String?
  let keywordSeeds: [String]
  let characterID: String
  let locationID: String

  enum CodingKeys: String, CodingKey {
    case id, title, subtitle, story, icon, imageAsset
    case chapterID = "chapterId"
    case keywordSeeds = "keywordSeeds"
    case characterID = "characterId"
    case locationID = "locationId"
  }
}

struct RuntimeStudyPath {
  let chapters: [AdventureChapter]
  let situations: [Situation]
}
